from locations.location import Location

LOCATIONS = {
    (1,5): Location((1,5), '[Basilica Ulpia: West Wing]', 'Sconces on the walls dimly illuminate the limestone pillars to the south, which lead outside.'),
    (1,6): Location((1,6), '[Basilica Ulpia: Gallery]', 'The beige limestone walls are covered in elaborate artwork. A huge stone archway on the south wall leads to the Basilica Courtyard.'),
    (1,7): Location((1,7), '[Basilica Ulpia: East Wing]', 'Sconces on the walls dimly illuminate the limestone pillars to the south, which lead outside.'),
    (2,5): Location((2,5), '[Outside The Basilica]', 'Cliffs to the south overlook the vast lands below. Off to the west, the orange glow of campfires can be seen in the distance.'),
    (2,6): Location((2,6), '[Basilica, Courtyard]', 'A winding path through the Basilica gardens leads northward to the gallery, while cliffs to the south overlook the vast lands below.'),
    (2,7): Location((2,7), '[Outside The Basilica]', 'Cliffs to the south overlook the vast lands below. Clear signs of life can be seen and heard from the southeast'),
    (3,2): Location((3,2), '[Bandit Camp]', 'Tall flames lick the skies all around you. Piles of human remains are randomly scattered between the fires.'),
    (3,5): Location((3,5), '[Bandit Camp, Palisades]', 'Fires rage beyond the palisades of the encampment, which are adorned with dozens of severed heads.'),
    (3,9): Location((3,9), ),
   (3,10): Location((3,10), ),
    (4,2): Location((4,2), ),
    (4,3): Location((4,3), ),
    (4,4): Location((4,4), ),
    (4,5): Location((4,5), ),
   (4,10): Location((4,10), ),
    (5,5): Location((5,5), ),
   (5,10): Location((5,10), ),
    (6,5): Location((6,5), ),
    (6,7): Location((6,7), ),
    (6,8): Location((6,8), ),
    (6,9): Location((6,9), ),
   (6,10): Location((6,10), ),
    (7,5): Location((7,5), ),
    (7,6): Location((7,6), ),
    (7,7): Location((7,7), ),
    (8,1): Location((8,1), ),
    (8,2): Location((8,2), ),
    (8,4): Location((8,4), ),
    (8,5): Location((8,5), ),
    (8,7): Location((8,7), ),
    (9,2): Location((9,2), ),
    (9,3): Location((9,3), ),
    (9,4): Location((9,4), ),
    (9,7): Location((9,7), ),
    (9,9): Location((9,9), ),
   (9,10): Location((9,10), ),
   (10,7): Location((10,7), ),
   (10,8): Location((10,8), ),
   (10,9): Location((10,9), ) 
}